//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video_Games_Rental.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public int request_id { get; set; }
        public string name { get; set; }
        public string e_mail { get; set; }
        public string request1 { get; set; }
        public string phonenumber { get; set; }
    }
}
